# See config.example.yml for documentation.
name: mk64-vc
object: orig/mk64-u/content1.app
hash: abac17998a900f386526aaa8a74f76ffbf5b0f92
symbols: config/mk64-u/symbols.txt
splits: config/mk64-u/splits.txt

# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 14

# extract:
# # DSPCode.c
# - symbol: axDspSlave
#   header: axDspSlave.inc
# # AXComp.c
# - symbol: __AXCompressorTable
#   header: __AXCompressorTable.inc

# force_active:
# - lbl_801E3380
# - DemoAllocator2

# block_relocations:
