# See config.example.yml for documentation.
name: wii-vc
object: orig/mk64-e/content1.app
hash: 106402a53dd9bc5d01d5b43079348a35b442990b
symbols: config/mk64-e/symbols.txt
splits: config/mk64-e/splits.txt

# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 14

# extract:
# # DSPCode.c
# - symbol: axDspSlave
#   header: axDspSlave.inc
# # AXComp.c
# - symbol: __AXCompressorTable
#   header: __AXCompressorTable.inc

# force_active:
# - lbl_801E3380
# - DemoAllocator2

# block_relocations:
