# See config.example.yml for documentation.
name: wii-vc
object: orig/mm-u/content1.app
hash: 85389116e4ae15448ce8d0ea77c37a920043903c
symbols: config/mm-u/symbols.txt
splits: config/mm-u/splits.txt

# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 14

# extract:
# # DSPCode.c
# - symbol: axDspSlave
#   header: axDspSlave.inc
# # AXComp.c
# - symbol: __AXCompressorTable
#   header: __AXCompressorTable.inc

# force_active:
# - lbl_801E3380
# - DemoAllocator2

# block_relocations:
# system.c
