# See config.example.yml for documentation.
name: wii-vc
object: orig/mk64-j/content1.app
hash: bfa2416d69894fce8614b580e6897b3658c1762c
symbols: config/mk64-j/symbols.txt
splits: config/mk64-j/splits.txt

# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 14

# extract:
# # DSPCode.c
# - symbol: axDspSlave
#   header: axDspSlave.inc
# # AXComp.c
# - symbol: __AXCompressorTable
#   header: __AXCompressorTable.inc

# force_active:
# - lbl_801E3380
# - DemoAllocator2

# block_relocations:
