name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/Yanis002/oot-gc-vc-build:main # temp!
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository (shallow clone)
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    # Set Git config
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # Copy the original files to the workspace
    - name: Prepare
      run: cp -R /orig .

    # Build the project
    - name: Build
      run: |
        python configure.py --map --binutils /binutils --compilers /compilers
        ninja all_source build/{sm64-j,sm64-u,sm64-e,mk64-j,mk64-u,mk64-e,oot-j,oot-u,oot-e}/progress.json build/report.json

    # Upload map files
    - name: Upload map
      uses: actions/upload-artifact@v4
      with:
        name: combined_maps
        path: build/**/*.MAP

    # Upload progress report
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: combined_report
        path: build/report.json
